name: ci

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - '.github/workflows/**'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: bash ./third_party/openFrameworks/scripts/osx/download_libs.sh && make -j4

  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: build
        run: |
          wget -O third_party/openFrameworks.tar.gz https://github.com/openframeworks/openFrameworks/releases/download/0.11.2/of_v0.11.2_linux64gcc6_release.tar.gz
          tar -xzvf third_party/openFrameworks.tar.gz -C third_party --strip-components=1 --one-top-level=openFrameworks
          sudo third_party/openFrameworks/scripts/linux/ubuntu/install_dependencies.sh
          sudo third_party/openFrameworks/scripts/linux/ubuntu/install_codecs.sh
          make -j4
